### ISSUE TITLE
Installation instruction incorrect?

### ISSUE THREAD

**Issue by mikkelzzz3** [Shraymonks/unmonitorr#2]
Hi, 
copy/pasting the installation instructions I got the following error:
services.unmonitorr.environment must be a mapping

As the "Key: Value" mapping syntax is used, no dash should be there. Dash should only be there if it was a list. As i "- Key=Value". Removing the dashes fixed my issue.

**Comment by mikkelzzz3** [comment]
Though after fixing the docker file I can't get it to work. :/ 
@Shraymonks would you possible be able to tell me what I am doing wrong? 

I have the following docker-compose.yml:
```
version: '3.8'
services:
  unmonitorr:
    image: shraymonks/unmonitorr:latest
    container_name: unmonitorr
    environment:
      PLEX_EVENTS: media.pause
      RADARR_HOST: http://127.0.0.1:7878
      RADARR_API_KEY: CENSORED
      SONARR_HOST: http://127.0.0.1:8989
      SONARR_API_KEY: CENSORED
    ports:
      - 9797:9797
    restart: unless-stopped
```

(I'm using media.pause so I can quickly test if it works or not, as it should unmonitor what I am watching as soon as I pause.)

I have the following webhook setup in plex: `http://localhost:9797`

Docker ps:
```
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS             PORTS                    NAMES
ae6e0a3d1e62   shraymonks/unmonitorr:latest   "dumb-init node dist…"   13 minutes ago   Up 13 minutes      0.0.0.0:9797->9797/tcp   unmonitorr
```

Logs:
```
root@user:/opt/unmonitorr# docker logs unmonitorr
unmonitoring for media.pause on port: 9797
Radarr: http://127.0.0.1:7878
Sonarr: http://127.0.0.1:8989
```

I really appreciate any help you are willing to give!
